language: python
python:
  - 2.6
  - 2.7
  - 3.3
before_install:
  - sudo apt-get update -qq
  - export PIP_USE_MIRRORS=true
  - pip install coveralls
install:
  - "pip install -e ."
# script: python setup.py test
script: coverage run --source=libunihan setup.py test
after_success:
  - coveralls
